---
title: "Prueba deflactar"
author: "Gabriel Diner"
date: "2023-08-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

Inflacion <- read_delim("Data/inflacioneta.csv", 
    delim = ";", escape_double = FALSE, locale = locale(encoding = "WINDOWS-1252"), 
    trim_ws = TRUE) 
```

```{r}
Inflacion <- Inflacion %>%
  mutate(periodo_fecha = as.Date(periodo_fecha, format = "%d/%m/%Y"))
deflactor <- inner_join(Comparativo, Inflacion, by = "periodo_fecha")
deflactor <- deflactor %>% 
  mutate(clt_deflactado = costo_laboral_total / inflacion_acumulada) %>% 
  mutate(cla_deflactado = suma_costo_laboral_Autoridades / inflacion_acumulada) 
deflactor <- deflactor %>% 
  mutate(cla_deflactado_base_100 = cla_deflactado * 100 / 779578029) %>% 
  mutate(clt_deflactado_base_100 = clt_deflactado * 100 / 172981400000)
deflactor %>% 
  ggplot(aes(x = periodo_fecha)) +
  geom_line(aes(y = clt_deflactado_base_100)) + 
  geom_point(aes(y = clt_deflactado_base_100)) +
  scale_x_date(date_breaks = "1 year", date_labels = "%y") +
  labs(title = "Comparativo Costo Laboral Funcionarios y Costo Laboral Total") +
  ylab("Costo Laboral") +
  xlab("Año") +
  labs(color = "Costo Laboral") +
  theme(legend.position = "bottom")
```

```{r}
Inflacion %>% 
  ggplot(aes(Periodo_fecha, Inflacion_acumulada)) +
  geom_line() + 
  geom_point() +
  geom_smooth() +
  labs(title = "Costo Laboral Total") +
  ylab("Costo Laboral") +
  xlab("Año") +
  labs(color = "Costo Laboral") +
  theme(legend.position = "bottom")
```

